name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-lint-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: npm test

      - run: npm run lint
        if: matrix.os == 'ubuntu-latest'

      - run: npm run format
        if: matrix.os == 'ubuntu-latest'

      - run: npm run build:docs
        # Only generate docs once on ubuntu.
        if: matrix.os == 'ubuntu-latest'

      - id: docs-deployment
        # Only upload docs once on ubuntu.
        # NOTE that this will not deploy docs, there's a separate job for that, that runs on main only.
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
          retention-days: 7

  deploy-docs:
    if: github.repository == 'nexus-rpc/sdk-typescript' && github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.docs-deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-lint-test
    steps:
      - name: Deploy to GitHub Pages
        id: docs-deployment
        uses: actions/deploy-pages@v4
